"""
Scaffold ho_api/ for a Litestar-backed halfORM project.

Files always regenerated:
  ho_api/app.py             — application entry point
  ho_api/authorization.py   — JWT middleware (reads HO_JWT_SECRET from env)
  ho_api/.env.example       — documents required environment variables

Files scaffolded once (never overwritten):
  ho_api/custom/middlewares/jwt_config.py — developer hook: enrich_state()
  ho_api/.env                             — secret values (must be gitignored)
"""

import secrets
from pathlib import Path

# ---------------------------------------------------------------------------
# ho_api/app.py  (always regenerated)
# ---------------------------------------------------------------------------

_APP_TEMPLATE = """\
import os
import sys

cur_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, cur_dir)
par_dir = os.path.join(cur_dir, os.path.pardir)
sys.path.insert(0, par_dir)

# Load ho_api/.env if present (env vars already set take precedence)
_env_file = os.path.join(cur_dir, '.env')
if os.path.isfile(_env_file):
    with open(_env_file) as _f:
        for _line in _f:
            _line = _line.strip()
            if _line and not _line.startswith('#') and '=' in _line:
                _k, _, _v = _line.partition('=')
                os.environ.setdefault(_k.strip(), _v.strip())

from half_orm_gen.backend.litestar.v2.runtime import build_crud_app
from {module_name} import MODEL

from ho_api.authorization import Authorization

_middleware: list = [Authorization]
_route_handlers: list = []

try:
    from ho_api.custom.middlewares import middlewares as _extra_middleware
    _middleware = _middleware + _extra_middleware
except ImportError:
    pass

try:
    from ho_api.custom.routes import routes as _route_handlers
except ImportError:
    pass

application = build_crud_app(
    MODEL,
    module_name='{module_name}',
    api_version={api_version},
    middleware=_middleware,
    route_handlers=_route_handlers,
)
"""

# ---------------------------------------------------------------------------
# ho_api/authorization.py  (always regenerated)
# ---------------------------------------------------------------------------

_AUTHORIZATION_TEMPLATE = """\
\"\"\"
JWT authorization middleware — generated by half_orm gen api.

On each request:
  1. Decode the Bearer JWT using HO_JWT_SECRET / HO_JWT_ALGORITHM.
  2. Set request.state.user             = payload['sub']
  3. Set request.state.authorized_roles = payload.get('roles', ['connected'])
     (route handlers expand the hierarchy via _expand_roles at call time)
  4. Call enrich_state(payload, state) if jwt_config.py provides it.

Fails at startup with a clear error if HO_JWT_SECRET is not set.

To add extra claims to request.state, create:
  ho_api/custom/middlewares/jwt_config.py
with:
  async def enrich_state(payload: dict, state: dict) -> None: ...
\"\"\"
import os
import uuid as _uuid

import jwt as _jwt
from litestar.types import ASGIApp, Receive, Scope, Send

_SECRET    = os.environ.get('HO_JWT_SECRET')
_ALGORITHM = os.environ.get('HO_JWT_ALGORITHM', 'HS256')

if not _SECRET:
    raise RuntimeError(
        'HO_JWT_SECRET environment variable is not set.\\n'
        'Add it to ho_api/.env (see .env.example) and make sure it is '
        'exported before starting the server.'
    )

try:
    from ho_api.custom.middlewares.jwt_config import enrich_state as _enrich_state
except ImportError:
    async def _enrich_state(payload: dict, state: dict) -> None:  # type: ignore[misc]
        pass


class Authorization:
    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope['type'] == 'http':
            from litestar.connection import Request
            token = (
                Request(scope)
                .headers.get('Authorization', '')
                .removeprefix('Bearer ')
                .strip()
            )
            state: dict = scope.setdefault('state', {})
            if token:
                try:
                    payload = _jwt.decode(token, _SECRET, algorithms=[_ALGORITHM])
                    user_id = payload.get('sub')
                    if user_id:
                        try:
                            state['user'] = _uuid.UUID(user_id)
                        except (ValueError, AttributeError):
                            state['user'] = user_id
                    # Store explicit roles — route handlers expand the hierarchy
                    state['authorized_roles'] = payload.get('roles', ['connected'])
                    await _enrich_state(payload, state)
                except _jwt.PyJWTError:
                    state['authorized_roles'] = ['anonymous']
            else:
                state['authorized_roles'] = ['anonymous']
        await self.app(scope, receive, send)
"""

# ---------------------------------------------------------------------------
# ho_api/.env.example  (always regenerated)
# ---------------------------------------------------------------------------

_ENV_EXAMPLE = """\
# Required — JWT signing secret. Generate with: python -c "import secrets; print(secrets.token_hex(32))"
HO_JWT_SECRET=

# Optional — JWT algorithm (default: HS256)
# HO_JWT_ALGORITHM=HS256
"""

# ---------------------------------------------------------------------------
# ho_api/custom/middlewares/jwt_config.py  (scaffolded once)
# ---------------------------------------------------------------------------

_JWT_CONFIG_TEMPLATE = """\
\"\"\"
Developer hook for the JWT authorization middleware.
Scaffolded once by `half_orm gen api` — never overwritten.

Implement enrich_state to add extra JWT claims to request.state
for use in application-level route handlers.
\"\"\"


async def enrich_state(payload: dict, state: dict) -> None:
    \"\"\"Add extra decoded claims to request.state.

    Examples:
        state['tenant_id'] = payload.get('tenant_id')
        state['email']     = payload.get('email')
    \"\"\"
"""


def scaffold_api_dir(
    api_dir: Path,
    module_name: str = '',
    api_version: int | None = None,
) -> None:
    """Write ho_api/app.py and authorization.py. Always regenerated."""
    api_dir.mkdir(parents=True, exist_ok=True)
    version_str = str(api_version) if api_version is not None else 'None'

    # app.py — always regenerated
    app_py = api_dir / 'app.py'
    content = (
        _APP_TEMPLATE
        .replace('{module_name}', module_name)
        .replace('{api_version}', version_str)
    )
    app_py.write_text(content, encoding='utf-8')
    print(f'  updated  {app_py}')

    # authorization.py — always regenerated
    auth_py = api_dir / 'authorization.py'
    auth_py.write_text(_AUTHORIZATION_TEMPLATE, encoding='utf-8')
    print(f'  updated  {auth_py}')

    # .env.example — always regenerated
    env_example = api_dir / '.env.example'
    env_example.write_text(_ENV_EXAMPLE, encoding='utf-8')
    print(f'  updated  {env_example}')

    # .env — scaffolded once with a random secret
    env_file = api_dir / '.env'
    if not env_file.exists():
        secret = secrets.token_hex(32)
        env_file.write_text(f'HO_JWT_SECRET={secret}\n', encoding='utf-8')
        print(f'  created  {env_file}  (gitignore this file!)')

    # jwt_config.py — scaffolded once
    jwt_config = api_dir / 'custom' / 'middlewares' / 'jwt_config.py'
    if not jwt_config.exists():
        jwt_config.parent.mkdir(parents=True, exist_ok=True)
        jwt_config.write_text(_JWT_CONFIG_TEMPLATE, encoding='utf-8')
        # ensure __init__.py files exist
        for init in (
            api_dir / 'custom' / '__init__.py',
            api_dir / 'custom' / 'middlewares' / '__init__.py',
        ):
            if not init.exists():
                init.write_text('', encoding='utf-8')
        print(f'  created  {jwt_config}')
